MOUSEKEY_ENABLE = yes       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
COMMAND_ENABLE = yes
NKRO_ENABLE = yes           # Enable N-Key Rollover
VIA_ENABLE = yes 	    #If you wish to use the VIA keymap
AUTO_SHIFT_ENABLE = no      #Auto Shift support
ENCODER_MAP_ENABLE = yes    #Rotary Encoder Support
RGBLIGHT_ENABLE = yes       #If backlights are installed
PIN_COMPATIBLE = elite_c    #Pin layout requirement
CONVERT_TO = elite_pi #If using RP2040 (Elite-pi or compatible board)
BOOTMAGIC_ENABLE = yes
